//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utalca.ControlAsistencia {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Curso", Namespace="http://schemas.datacontract.org/2004/07/ControlAsistencia")]
    [System.SerializableAttribute()]
    public partial class Curso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utalca.ControlAsistencia.Participante[] AlumnosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utalca.ControlAsistencia.Participante[] AyudantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utalca.ControlAsistencia.Carrera CarreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utalca.ControlAsistencia.Clase[] HorarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utalca.ControlAsistencia.Plan PlanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utalca.ControlAsistencia.Participante[] ProfesoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utalca.ControlAsistencia.Curso[] RequisitosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utalca.ControlAsistencia.Syllabus SyllabusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utalca.ControlAsistencia.Participante[] Alumnos {
            get {
                return this.AlumnosField;
            }
            set {
                if ((object.ReferenceEquals(this.AlumnosField, value) != true)) {
                    this.AlumnosField = value;
                    this.RaisePropertyChanged("Alumnos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utalca.ControlAsistencia.Participante[] Ayudantes {
            get {
                return this.AyudantesField;
            }
            set {
                if ((object.ReferenceEquals(this.AyudantesField, value) != true)) {
                    this.AyudantesField = value;
                    this.RaisePropertyChanged("Ayudantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utalca.ControlAsistencia.Carrera Carrera {
            get {
                return this.CarreraField;
            }
            set {
                if ((object.ReferenceEquals(this.CarreraField, value) != true)) {
                    this.CarreraField = value;
                    this.RaisePropertyChanged("Carrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Creditos {
            get {
                return this.CreditosField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditosField, value) != true)) {
                    this.CreditosField = value;
                    this.RaisePropertyChanged("Creditos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utalca.ControlAsistencia.Clase[] Horario {
            get {
                return this.HorarioField;
            }
            set {
                if ((object.ReferenceEquals(this.HorarioField, value) != true)) {
                    this.HorarioField = value;
                    this.RaisePropertyChanged("Horario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagenURL {
            get {
                return this.ImagenURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenURLField, value) != true)) {
                    this.ImagenURLField = value;
                    this.RaisePropertyChanged("ImagenURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utalca.ControlAsistencia.Plan Plan {
            get {
                return this.PlanField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanField, value) != true)) {
                    this.PlanField = value;
                    this.RaisePropertyChanged("Plan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utalca.ControlAsistencia.Participante[] Profesores {
            get {
                return this.ProfesoresField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfesoresField, value) != true)) {
                    this.ProfesoresField = value;
                    this.RaisePropertyChanged("Profesores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utalca.ControlAsistencia.Curso[] Requisitos {
            get {
                return this.RequisitosField;
            }
            set {
                if ((object.ReferenceEquals(this.RequisitosField, value) != true)) {
                    this.RequisitosField = value;
                    this.RaisePropertyChanged("Requisitos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seccion {
            get {
                return this.SeccionField;
            }
            set {
                if ((object.ReferenceEquals(this.SeccionField, value) != true)) {
                    this.SeccionField = value;
                    this.RaisePropertyChanged("Seccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utalca.ControlAsistencia.Syllabus Syllabus {
            get {
                return this.SyllabusField;
            }
            set {
                if ((object.ReferenceEquals(this.SyllabusField, value) != true)) {
                    this.SyllabusField = value;
                    this.RaisePropertyChanged("Syllabus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Carrera", Namespace="http://schemas.datacontract.org/2004/07/ControlAsistencia")]
    [System.SerializableAttribute()]
    public partial class Carrera : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plan", Namespace="http://schemas.datacontract.org/2004/07/ControlAsistencia")]
    [System.SerializableAttribute()]
    public partial class Plan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Syllabus", Namespace="http://schemas.datacontract.org/2004/07/ControlAsistencia")]
    [System.SerializableAttribute()]
    public partial class Syllabus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Participante", Namespace="http://schemas.datacontract.org/2004/07/ControlAsistencia")]
    [System.SerializableAttribute()]
    public partial class Participante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clase", Namespace="http://schemas.datacontract.org/2004/07/ControlAsistencia")]
    [System.SerializableAttribute()]
    public partial class Clase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utalca.ControlAsistencia.Participante[] PresentesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Utalca.ControlAsistencia.Recurso SalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utalca.ControlAsistencia.Participante[] Presentes {
            get {
                return this.PresentesField;
            }
            set {
                if ((object.ReferenceEquals(this.PresentesField, value) != true)) {
                    this.PresentesField = value;
                    this.RaisePropertyChanged("Presentes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Utalca.ControlAsistencia.Recurso Sala {
            get {
                return this.SalaField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaField, value) != true)) {
                    this.SalaField = value;
                    this.RaisePropertyChanged("Sala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recurso", Namespace="http://schemas.datacontract.org/2004/07/ControlAsistencia")]
    [System.SerializableAttribute()]
    public partial class Recurso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ControlAsistencia.IControlAsistencia")]
    public interface IControlAsistencia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlAsistencia/Cursos", ReplyAction="http://tempuri.org/IControlAsistencia/CursosResponse")]
        Utalca.ControlAsistencia.Curso[] Cursos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlAsistencia/Cursos", ReplyAction="http://tempuri.org/IControlAsistencia/CursosResponse")]
        System.Threading.Tasks.Task<Utalca.ControlAsistencia.Curso[]> CursosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlAsistencia/Curso", ReplyAction="http://tempuri.org/IControlAsistencia/CursoResponse")]
        Utalca.ControlAsistencia.Curso Curso(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlAsistencia/Curso", ReplyAction="http://tempuri.org/IControlAsistencia/CursoResponse")]
        System.Threading.Tasks.Task<Utalca.ControlAsistencia.Curso> CursoAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlAsistencia/CursosPorProfesor", ReplyAction="http://tempuri.org/IControlAsistencia/CursosPorProfesorResponse")]
        Utalca.ControlAsistencia.Curso[] CursosPorProfesor(long idProfesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlAsistencia/CursosPorProfesor", ReplyAction="http://tempuri.org/IControlAsistencia/CursosPorProfesorResponse")]
        System.Threading.Tasks.Task<Utalca.ControlAsistencia.Curso[]> CursosPorProfesorAsync(long idProfesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlAsistencia/RegistrarAsistencia", ReplyAction="http://tempuri.org/IControlAsistencia/RegistrarAsistenciaResponse")]
        bool RegistrarAsistencia(long idParticipante, long idCurso, long fechaClase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlAsistencia/RegistrarAsistencia", ReplyAction="http://tempuri.org/IControlAsistencia/RegistrarAsistenciaResponse")]
        System.Threading.Tasks.Task<bool> RegistrarAsistenciaAsync(long idParticipante, long idCurso, long fechaClase);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IControlAsistenciaChannel : Utalca.ControlAsistencia.IControlAsistencia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControlAsistenciaClient : System.ServiceModel.ClientBase<Utalca.ControlAsistencia.IControlAsistencia>, Utalca.ControlAsistencia.IControlAsistencia {
        
        public ControlAsistenciaClient() {
        }
        
        public ControlAsistenciaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControlAsistenciaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlAsistenciaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlAsistenciaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Utalca.ControlAsistencia.Curso[] Cursos() {
            return base.Channel.Cursos();
        }
        
        public System.Threading.Tasks.Task<Utalca.ControlAsistencia.Curso[]> CursosAsync() {
            return base.Channel.CursosAsync();
        }
        
        public Utalca.ControlAsistencia.Curso Curso(long id) {
            return base.Channel.Curso(id);
        }
        
        public System.Threading.Tasks.Task<Utalca.ControlAsistencia.Curso> CursoAsync(long id) {
            return base.Channel.CursoAsync(id);
        }
        
        public Utalca.ControlAsistencia.Curso[] CursosPorProfesor(long idProfesor) {
            return base.Channel.CursosPorProfesor(idProfesor);
        }
        
        public System.Threading.Tasks.Task<Utalca.ControlAsistencia.Curso[]> CursosPorProfesorAsync(long idProfesor) {
            return base.Channel.CursosPorProfesorAsync(idProfesor);
        }
        
        public bool RegistrarAsistencia(long idParticipante, long idCurso, long fechaClase) {
            return base.Channel.RegistrarAsistencia(idParticipante, idCurso, fechaClase);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarAsistenciaAsync(long idParticipante, long idCurso, long fechaClase) {
            return base.Channel.RegistrarAsistenciaAsync(idParticipante, idCurso, fechaClase);
        }
    }
}
